const position = { x: 0, y: 0 };
const edgeType = "smoothstep";

export const initialNodes = [
  {
    id: "dashboard",
    type: "dashboardNode",
    data: { label: "dashbboard" },
    position,
  },
  {
    id: "allSVG",
    type: "customCombinedNodeSVG",
    data: { label: "allSVG" },
    position,
  },
  {
    id: "0",
    type: "customGeneralNodeLeftTarget",
    data: { label: "input" },
    position,
  },
  {
    id: "0a",
    type: "customGeneralNodeLeftTarget",
    data: { label: "0a" },
    position,
  },
  {
    id: "0b",
    type: "nodesOnRight",
    data: { label: "0b" },
    position,
  },
  {
    id: "0c",
    type: "customGeneralNodeLeftTarget",
    data: { label: "0c" },
    position,
  },
  {
    id: "0a1a",
    type: "nodesOnTop",
    data: { label: "0a1a" },
    position,
  },
  {
    id: "0a1b",
    type: "nodesOnRight",
    data: { label: "0a1b" },
    position,
  },
  // added three nodes here
  {
    id: "0a1b2a",
    type: "nodesOnTop",
    data: { label: "0a1b2a" },
    position,
  },
  {
    id: "0a1b2b",
    type: "nodesOnRight",
    data: { label: "0a1b2b" },
    position,
  },
  {
    id: "0a1b2c",
    type: "nodesOnBottom",
    data: { label: "0a1b2c" },
    position,
  },
  {
    id: "0a1c",
    type: "nodesOnBottom",
    data: { label: "0a1c" },
    position,
  },
  {
    id: "0b1a",
    type: "nodesOnTop",
    data: { label: "0b1a" },
    position,
  },
  // added three nodes here
  {
    id: "0b1a2a",
    type: "nodesOnTop",
    data: { label: "0b1a2a" },
    position,
  },
  {
    id: "0b1a2b",
    type: "nodesOnRight",
    data: { label: "0b1a2b" },
    position,
  },
  // {
  //   id: "0b1a2c",
  //   type: "nodesOnBottom",
  //   data: { label: "0b1a2c" },
  //   position,
  // },
  {
    id: "0b1b",
    type: "nodesOnRight",
    data: { label: "0b1b" },
    position,
  },
  {
    id: "0b1c",
    type: "nodesOnBottom",
    data: { label: "0b1c" },
    position,
  },
  {
    id: "0c1a",
    type: "nodesOnTop",
    data: { label: "0c1a" },
    position,
  },
  {
    id: "0c1b",
    type: "nodesOnRight",
    data: { label: "0c1b" },
    position,
  },
  {
    id: "0c1c",
    type: "nodesOnBottom",
    data: { label: "0c1c" },
    position,
  },
];

export const initialEdges = [
  {
    id: "eallSVG0",
    source: "allSVG",
    target: "0",
    type: edgeType,
    animated: true,
  },
  {
    id: "e00a",
    source: "0",
    target: "0a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e00b",
    source: "0",
    target: "0b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e00c",
    source: "0",
    target: "0c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  {
    id: "e0a0a1a",
    source: "0a",
    target: "0a1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0a1b",
    source: "0a",
    target: "0a1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0a1c",
    source: "0a",
    target: "0a1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  {
    id: "e0a0b1a",
    source: "0b",
    target: "0b1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0b1b",
    source: "0b",
    target: "0b1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0b1c",
    source: "0b",
    target: "0b1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  // adding three edges here
  {
    id: "e0b0b1a2a",
    source: "0b1a",
    target: "0b1a2a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0b0b1a2b",
    source: "0b1a",
    target: "0b1a2b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  // {
  //   id: "e0b0b1a2c",
  //   source: "0b1a",
  //   target: "0b1a2c",
  //   type: edgeType,
  //   animated: true,
  //   sourceHandle: "c",
  // },
  {
    id: "e0a0c1a",
    source: "0c",
    target: "0c1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0c1b",
    source: "0c",
    target: "0c1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0c1c",
    source: "0c",
    target: "0c1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  // adding three edges here
  {
    id: "e0a0a1b2a",
    source: "0a1b",
    target: "0a1b2a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0a1b2b",
    source: "0a1b",
    target: "0a1b2b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0a1b2c",
    source: "0a1b",
    target: "0a1b2c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  // connecting dashboard
  {
    id: "e0adashboard",
    source: "0a",
    target: "dashboard",
    type: edgeType,
    animated: true,
    sourceHandle: "dash",
    targetHandle: "d",
  },
  {
    id: "e0a1adashboard",
    source: "0a1a",
    target: "dashboard",
    type: edgeType,
    animated: true,
    sourceHandle: "dash",
    targetHandle: "d",
  },
  {
    id: "e0a1b2adashboard",
    source: "0a1b2a",
    target: "dashboard",
    type: edgeType,
    animated: true,
    sourceHandle: "dash",
    targetHandle: "c",
  },
];
