const position = { x: 0, y: 0 };
const edgeType = "smoothstep";

export const initialNodes = [
  {
    id: "allSVG",
    type: "customGeneralNodeLeftTarget",
    data: { label: "allSVG" },
    position,
  },
  {
    id: "0",
    type: "customGeneralNodeLeftTarget",
    data: { label: "input" },
    position,
  },
  {
    id: "0a",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0a" },
    position,
  },
  {
    id: "0b",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0b" },
    position,
  },
  {
    id: "0c",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0c" },
    position,
  },
  {
    id: "0a1a",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0a1a" },
    position,
  },
  {
    id: "0a1b",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0a1b" },
    position,
  },
  {
    id: "0a1c",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0a1c" },
    position,
  },
  {
    id: "0b1a",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0b1a" },
    position,
  },
  {
    id: "0b1b",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0b1b" },
    position,
  },
  {
    id: "0b1c",
    type: "nodesOnBottom",
    data: { label: "node 0b1c" },
    position,
  },
  {
    id: "0c1a",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0c1a" },
    position,
  },
  {
    id: "0c1b",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0c1b" },
    position,
  },
  {
    id: "0c1c",
    type: "customGeneralNodeLeftTarget",
    data: { label: "node 0c1c" },
    position,
  },
];

export const initialEdges = [
  {
    id: "eallSVG0",
    source: "allSVG",
    target: "0",
    type: edgeType,
    animated: true,
  },
  {
    id: "e00a",
    source: "0",
    target: "0a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e00b",
    source: "0",
    target: "0b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e00c",
    source: "0",
    target: "0c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  {
    id: "e0a0a1a",
    source: "0a",
    target: "0a1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0a1b",
    source: "0a",
    target: "0a1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0a1c",
    source: "0a",
    target: "0a1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  {
    id: "e0a0b1a",
    source: "0b",
    target: "0b1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0b1b",
    source: "0b",
    target: "0b1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0b1c",
    source: "0b",
    target: "0b1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
  {
    id: "e0a0c1a",
    source: "0c",
    target: "0c1a",
    type: edgeType,
    animated: true,
    sourceHandle: "a",
  },
  {
    id: "e0a0c1b",
    source: "0c",
    target: "0c1b",
    type: edgeType,
    animated: true,
    sourceHandle: "b",
  },
  {
    id: "e0a0c1c",
    source: "0c",
    target: "0c1c",
    type: edgeType,
    animated: true,
    sourceHandle: "c",
  },
];
